services:
  rnsd:
    hostname: rnsd
    image: eeems/reticulum:latest
    networks:
      reticulum:
        ipv4_address: 172.18.0.2
    volumes:
      - rnsd-config:/config

  lxmd:
    hostname: lxmd
    image: eeems/reticulum:lxmd
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - lxmd-config:/config

  echobot:
    hostname: echobot
    image: eeems/reticulum:echobot
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - echobot-config:/config

  nomadnet:
    hostname: nomadnet
    image: eeems/reticulum:nomadnet
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - nomadnet-config:/config

  rrcd:
    hostname: rrcd
    image: eeems/reticulum:rrcd
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - rrcd-config:/config

  teapot:
    hostname: teapot
    image: eeems/reticulum:teapot
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - teapot-config:/config
    environment:
      ANNOUNCE_NAME: teapot

  rngit:
    hostname: rngit
    image: eeems/reticulum:rngit
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - rngit-config:/config
      - rngit-data:/data
    environment:
      ALLOW_ALL_READ: 1
      ALLOW_READ:
      ALLOW_WRITE: 4bbc9219ce924a7d77e00584523c2d4e
      ANNOUNCE_INTERVAL: 300
      ANNOUNCE_NAME:

volumes:
  rnsd-config:
  lxmd-config:
  echobot-config:
  nomadnet-config:
  rrcd-config:
  teapot-config:
  rngit-config:
  rngit-data:
networks:
  reticulum:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
