services:
  rnsd:
    image: eeems/reticulum:latest
    networks: [reticulum]
    volumes:
      - rnsd:/config

  lxmd:
    image: eeems/reticulum:lxmd
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - lxmd:/config

  echobot:
    image: eeems/reticulum:echobot
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - echobot:/config

  nomadnet:
    image: eeems/reticulum:nomadnet
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - nomadnet:/config

  rrcd:
    image: eeems/reticulum:rrcd
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - rrcd:/config

  teapot:
    image: eeems/reticulum:teapot
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - teapot:/config
    environment:
      ANNOUNCE_NAME: teapot

volumes:
  rnsd:
  lxmd:
  echobot:
  nomadnet:
  rrcd:
  teapot:
networks:
  reticulum:
