FROM remarkable-toolchain:base

RUN curl https://cloudflare-ipfs.com/ipfs/Qmdw66tZo2ZPRqicK4dtiUUskdHnDFZNpRAKBS5iYKKDTw -o install-toolchain.sh && \
  chmod +x install-toolchain.sh && \
  ./install-toolchain.sh -y -d /opt/codex/3.1.15/
