FROM eeems/remarkable-toolchain:base

RUN curl https://cloudflare-ipfs.com/ipfs/QmZmt4UtvyLLA8mLde6WspqvhMAKjzfvJW91R3bEja6y3A -o install-toolchain.sh && \
  chmod +x install-toolchain.sh && \
  ./install-toolchain.sh -y -d /opt/codex/1.8
