name: build
on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
            - LICENSE
    schedule:
        - cron: '0 */6 * * *'
    workflow_dispatch:
jobs:
    build:
        name: Publish latest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v3
            - uses: jpribyl/action-docker-layer-caching@v0.1.0
              continue-on-error: true
            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: registry.eeems.codes
                  username: github
                  password: ${{ secrets.CR_PAT }}
            - name: Build and publish images
              run: |
                docker system prune --force
                ./scripts/build images
                docker system prune --force
