name: build
on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 0 * * *'
jobs:
    build:
        name: Publish latest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Login to Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: registry.eeems.codes
                  username: github
                  password: ${{ secrets.CR_PAT }}
            - name: Build and publish images
              run: |
                ./scripts/build -p images
