name: build
on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
            - LICENSE
    schedule:
        - cron: '0 */6 * * *'
    workflow_dispatch:
jobs:
    build:
        name: Publish latest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v3
            - name: Login to registry.eeems.codes
              uses: docker/login-action@v2
              with:
                  registry: registry.eeems.codes
                  username: github
                  password: ${{ secrets.CR_PAT }}
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: eeems
                  password: ${{ secrets.DOCKER_AT }}
            - name: Install chronic
              id: cache-apt
              uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                packages: moreutils
                version: 1.0
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and publish images
              run: |
                docker system prune --force
                ./scripts/build -g images
                docker system prune --force
