name: build
on:
    push:
        branches:
            - v1.x
            - v2.x
jobs:
    build:
        name: Publish latest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Build and publish images
              run: |
                echo "${{ secrets.CR_PAT }}" | docker login registry.eeems.codes -u github --password-stdin
                ./scripts/build -p src
